import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";
import ThemeRegistry from "@/components/ThemeRegistry";
import { StoreProvider } from "@/components/StoreProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import { grayColor2 } from "@/constants/color";
import TrendingHeader from "@/components/trending/TrendingHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: grayColor2 }}
      >
        <StoreProvider>
          <AuthProvider>
            <ThemeRegistry>
              <div className="w-[80%] mx-auto">
                <TrendingHeader />
              </div>
              <div className="" style={{ backgroundColor: grayColor2 }}>
                {children}
              </div>
            </ThemeRegistry>
            <ToastProvider />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
